List<String> bio11=[
    "The Living World",
    "Biological Classification",
    "Plant Kingdom",
    "Animal Kingdom",
    "Morphology of Flowering Plants",
    "Anatomy of Flowering Plants",
    "Structural Organisation in Animals",
    "The Unit of Life",
    "BioMolecules",
    "Cell Cycle and Cell Division",
    "Transport in Plants",
    "Mineral Nutrition",
    "Photosynthesis in higher plants",
    "Respiration in Plants",
    "Plant Growth and Development",
    "Digestion And Absorption",
    "Breathing and Exchange of Gases",
    "Body fluids and circulation",
    "Excretory Products and their Elimination",
    "Locomotion and Movement",
    "Neural Control and Coordination",
    "Chemical Coordination and Integration"
    ];

List<String> phy11=[
  "Physical World",
  "Units and Measurements",
  "Motion in a Straight Line",
  "Motion in a Plane",
  "Laws of Motion",
  "Work, Energy and Power",
  "System of Particles and Rotational Motion",
  "Gravitation",
  "Mechanical Properties of Solids",
  "Mechanical Properties of Fluids",
  "Thermal Properties of Matter",
  "Thermodynamics",
  "Kinetic Theory",
  "Oscillations",
  "Waves",
];
List<String> che11=[
  "Basic Concepts of Chemistry",
  "Structure of Atom",
  "Classification of Elements & Periodicity in Properties",
  "Chemical Bonding and Molecular Structure",
  "States of Matter: Gases and Liquids",
  "Thermodynamics",
  "Equilibrium",
  "Redox Reactions",
  "Hydrogen",
  "s-Block Elements",
  "Some p-Block Elements",
  "Organic Chemistry: Basic Principles & Techniques",
  "Hydrocarbons",
  "Environmental Chemistry",
];
List<String> mth11=[
    "Sets",
    "Relations and Functions",
    "Trigonometric Functions",
    "Principle of Mathematical Induction",
    "Complex Numbers and Quadratic Equations",
    "Linear Inequalities",
    "Permutations and Combinations",
    "Binomial Theorem",
    "Sequences and Series",
    "Straight Lines",
    "Conic Sections",
    "Introduction to Three Dimensional Geometry",
    "Limits and Derivatives",
    "Mathematical Reasoning",
    "Statistics",
    "Probability"
];
List<String> bio12=[
    "Reproduction in Organisms",
    "Sexual Reproduction in Flowering Plants",
    "Human Reproduction",
    "Reproductive Health",
    "Principles of Inheritance and Variation",
    "Molecular Basis of Inheritance",
    "Evolution",
    "Human Health and Disease",
    "Strategies for Enhancement in Food Production",
    "Microbes in Human Welfare",
    "Biotechnology Principles and Processes",
    "Biotechnology and its Applications",
    "Organisms and Populations",
    "Ecosystem",
    "Biodiversity and Conservation",
    "Environmental Issues"
];
List<String> phy12=[
    "Electric Charges and Fields",
    "Electrostatic Potential and Capacitance",
    "Current Electricity",
    "Moving Charges and Magnetism",
    "Magnetism and Matter",
    "Electromagnetic Induction",
    "Alternating Current",
    "Electromagnetic Waves",
    "Ray Optics and Optical Instruments",
     "Wave Optics",
     "Dual Nature of Radiation and Matter",
     "Atoms",
     "Nuclei",
     "Semiconductors Electronics",
     "Communication Systems"
];
List<String> che12=[
  "Solutions",
  "Electrochemistry",
  "Chemical Kinetics",
  "Surface Chemistry",
  "General Principles and Processes of Isolation of Elements",
  "p-Block Elements",
  "d- and f-Block Elements",
  "Coordination Compounds",
  "Haloalkanes and Haloarenes",
  "Alcohols, Phenols, and Ethers",
  "Aldehydes, Ketones, and Carboxylic Acids",
  "Organic Compounds Containing Nitrogen",
  "Biomolecules",
  "Polymers",
  "Chemistry in Everyday Life"
];
List<String> mth12=[
  "Relations and Functions",
  "Inverse Trigonometric Functions",
  "Matrices",
  "Determinants",
  "Continuity and Differentiability",
  "Applications of Derivatives",
  "Integrals",
  "Applications of the Integrals",
  "Differential Equations",
  "Vectors",
  "Three-Dimensional Geometry",
  "Linear Programming",
  "Probability"
];